name: Windows-CRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'CRD code'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Assign User
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Alone215" -Force)
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }}
    - name: Keep Alive
      run: Test-Connection -TargetName www.google.com -Traceroute
